import 'package:gym_app/model/train_model.dart';

final mondayTrain = TrainModel(
  title: 'Peito e Tríceps',
  type: 'Máquina e halteres',
  time: 60,
  exerciseList: [
    ExerciseModel(
      group: 0,
      title: 'Supino reto',
      weight: 40,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Supino inclinado',
      weight: 20,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Crucifixo',
      weight: 12,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Voador',
      weight: 20,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Tríceps barra',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Tríceps corda',
      weight: 15,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Tríceps Máquina',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 2,
      title: 'Panturrilha',
      weight: 6,
      sets: 4,
      reps: 10,
    ),
  ],
);

final tuesdayTrain = TrainModel(
  title: 'Quadríceps e Posterior',
  type: 'Máquina',
  time: 45,
  exerciseList: [
    ExerciseModel(
      group: 0,
      title: 'Agachamento Smith',
      weight: 20,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Cadeira Extensora',
      weight: 40,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Leg 90',
      weight: 160,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Adutora',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Cadeira flexora',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Mesa flexora',
      weight: 20,
      sets: 4,
      reps: 10,
    ),
  ],
);

final wednesdayTrain = TrainModel(
  title: 'Costas e Bíceps',
  type: 'Máquina e halteres',
  time: 60,
  exerciseList: [
    ExerciseModel(
      group: 0,
      title: 'Puxada alta',
      weight: 40,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Remada aberta',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Remada fechada',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Puxada baixa',
      weight: 26,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Rosca martelo',
      weight: 14,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Rosca alternada',
      weight: 6,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Rosca direta',
      weight: 6,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 2,
      title: 'Panturrilha',
      weight: 6,
      sets: 4,
      reps: 10,
    ),
  ],
);

final thursdayTrain = TrainModel(
  title: 'Glúteos e Posterior',
  type: 'Máquina e livre',
  time: 45,
  exerciseList: [
    ExerciseModel(
      group: 0,
      title: 'Abdutora',
      weight: 30,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Agachamento',
      weight: 14,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Leg 45 aberta',
      weight: 35,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Leg 45 fechada',
      weight: 35,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Agachamento Hack',
      weight: 80,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Mesa flexora',
      weight: 20,
      sets: 4,
      reps: 10,
    ),
  ],
);

final fridayTrain = TrainModel(
  title: 'Ombros e Abdômem',
  type: 'Máquina e livre',
  time: 60,
  exerciseList: [
    ExerciseModel(
      group: 0,
      title: 'Desenvolvimento',
      weight: 12,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Elevação lateral',
      weight: 6,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 0,
      title: 'Desenvolvimento Arnold',
      weight: 8,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Abdominal infra',
      weight: 0,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Abdominal supra',
      weight: 5,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 1,
      title: 'Abdominal banco',
      weight: 0,
      sets: 4,
      reps: 10,
    ),
    ExerciseModel(
      group: 2,
      title: 'Panturrilha',
      weight: 6,
      sets: 4,
      reps: 10,
    ),
  ],
);
